config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'

  resources :groups
  resources :users, only: :index do
    post :upload, on: :collection
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: groups
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_groups_on_name  (name) UNIQUE
#
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :users_groups, dependent: :destroy
  has_many :users, through: :users_groups

  has_many :organizers_groups, -> { organizer }, class_name: 'UsersGroup', dependent: :destroy, inverse_of: :group
  has_many :organizers, through: :organizers_groups, source: :user, class_name: 'User'

  def organizers_names
    organizers.map(&:full_name)
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  first_name :string
#  last_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :users_groups, dependent: :destroy
  has_many :groups, through: :users_groups

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/users_group.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users_groups
#
#  id         :bigint           not null, primary key
#  role       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_users_groups_on_group_id                       (group_id)
#  index_users_groups_on_user_id                        (user_id)
#  index_users_groups_on_user_id_and_group_id_and_role  (user_id,group_id,role) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#  fk_rails_...  (user_id => users.id)
#
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :user_id, uniqueness: { scope: %i[role group_id] }

  enum role: { organizer: 0, presenter: 1, participant: 2 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from StandardError, with: :handle_standard_error
    rescue_from ActionController::ParameterMissing, with: :render_parameter_missing
    rescue_from ActionController::InvalidAuthenticityToken, with: :invalid_csrf_token
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
    rescue_from ActiveRecord::RecordNotUnique, with: :record_not_unique
  end

  private

  def invalid_csrf_token
    message = I18n.t('errors.failed_request_authenticity')

    respond_to_error(message)
  end

  def render_error
    message = I18n.t('errors.page_not_found')

    respond_to_error(message)
  end

  def record_not_found
    message = I18n.t('errors.records_not_found')

    respond_to_error(message)
  end

  def record_not_unique
    message = I18n.t('errors.duplicate')

    respond_to_error(message)
  end

  def render_parameter_missing(exception)
    message = I18n.t('errors.missing_param', param: exception.param.to_s)

    log_exception_backtrace(exception)
    respond_to_error(message)
  end

  def handle_standard_error(exception)
    message = exception.message || I18n.t('errors.server')

    log_exception_backtrace(exception)
    respond_to_error(message)
  end

  def user_not_authorized
    message = I18n.t('errors.unauthorize')

    respond_to_error(message)
  end

  def log_exception_backtrace(exception)
    return unless Rails.env.production?

    exception.backtrace.each { |line| Rails.logger.warn(line) }
  end

  def referer_or_root_path
    redirect_back_or_to root_path
  end

  def respond_to_error(message)
    respond_to do |format|
      format.html do
        flash.alert = message

        referer_or_root_path
      end

      format.turbo_stream do
        flash.now.alert = message

        render turbo_stream: [turbo_stream.replace(:messages, partial: 'shared/messages')]
      end
    end
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :set_users_group, only: :show
  before_action :set_groups, only: :index

  def index; end

  def show; end

  def new
    @group = Group.new
  end

  def edit; end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: I18n.t('group.create_success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: I18n.t('group.update_success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @group.destroy
      redirect_to groups_url, notice: I18n.t('group.destroy_success')
    else
      redirect_to groups_url, alert: I18n.t('group.destroy_failure')
    end
  end

  private

  def set_group
    @group = Group.includes(users_groups: :user).find(params[:id])
  end

  def set_users_group
    @pagy, @users_group = pagy(UsersGroup.includes(:user).where(group_id: @group.id))
  end

  def group_params
    params.require(:group).permit(:name)
  end

  def set_groups
    @pagy, @groups = pagy(Group.includes(:organizers).all)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index; end

  def upload
    uploaded_file = params[:file]

    if uploaded_file
      file_path = save_uploaded_file(uploaded_file)

      UsersImportJob.perform_later(file_path)
      redirect_to groups_path, notice: I18n.t('user.upload_success')
    else
      redirect_to users_path, alert: I18n.t('user.upload_file_not_selected')
    end
  end

  private

  def save_uploaded_file(uploaded_file)
    file_path = Rails.root.join('tmp', "uploaded_file_#{Time.current.to_i}_#{uploaded_file.original_filename}")
    File.binwrite(file_path, uploaded_file.read)
    file_path.to_s
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_form_errors.html.erb
<% if resource.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this form from being saved:</h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/groups/_delete_button.html.erb
<div>
  <%= button_to group, method: :delete, class: 'btn btn-danger' do %>
    <i class="bi bi-trash3-fill"></i>
  <% end %>
</div>

app/views/groups/_edit_button.html.erb
<div>
  <%= link_to edit_group_path(group), class: 'btn btn-primary' do %>
    <i class="bi bi-pencil-square"></i>
  <% end %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <%= render 'form_errors', resource: group %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control mb-3' %>
  </div>

  <div>
    <%= form.submit 'Save' , class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<tr>
  <td><%= group.name %></td>

  <td><%= render 'organizers', organizers: group.organizers_names %></td>

  <td class='d-flex gap-2'>
    <%= render 'show_button', group: group %>
    <%= render 'edit_button', group: group %>
    <%= render 'delete_button', group: group %>
  </td>
</tr>

app/views/groups/_group_user.html.erb
<tr>
  <td><%= group_user.user.full_name %></td>

  <td><%= group_user.role.titleize %></td>
</tr>

app/views/groups/_group_users.html.erb
<h4 class='mt-4'>Users</h4>

<table class="table">
  <thead>
    <tr>
      <th scope="col">User Name</th>
      <th scope="col">Role</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'group_user', collection: group_users %>
  </tbody>
</table>

<%== pagy_bootstrap_nav(pagy) if pagy.pages > 1 %>

app/views/groups/_organizers.html.erb
<div class='d-flex gap-3'>
  <% if organizers.present? %>
    <% organizers.each do |organizer| %>
      <h4 class='badge bg-secondary'><%= organizer %></h4>
    <% end %>
  <% else %>
    No Organizer!
  <% end %>
</div>

app/views/groups/_show_button.html.erb
<%= link_to 'View', group, class: 'btn btn-info text-white' %>

app/views/groups/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Organizer(s)</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'group', collection: groups %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= render 'show_button', group: @group %>
  <%= link_to "Back to groups", groups_path, class: 'btn btn-light' %>
</div>

app/views/groups/index.html.erb
<p style="color: green"><%= notice %></p>

<div class='d-flex justify-content-between align-items-center gap-3'>
  <h1>Groups</h1>

  <div>
    <%= link_to "Import Users", users_path, class: 'btn btn-secondary' %>
    <%= link_to "New Group", new_group_path, class: 'btn btn-primary' %>
  </div>
</div>



<div id="groups">
  <%= render 'table', groups: @groups %>

  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/groups/new.html.erb
<div class='w-50 border p-5 shadow-sm rounded mx-auto'>
  <h1>New Group</h1>

  <%= render "form", group: @group %>
  <br>

  <div>
    <%= link_to "Back to groups", groups_path, class: 'btn btn-light' %>
  </div>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<div class='d-flex align-items-center gap-2'>
  <h3>
    Name:
  </h3>
  <h4>
    <%= @group.name %>
  </h4>
</div>

<%= render 'group_users', group_users: @users_group, pagy: @pagy %>

<div class='mt-3 d-flex gap-3'>
  <%= render 'edit_button', group: @group %>
  <%= render 'delete_button', group: @group %>

  <%= link_to "Back to groups", groups_path, class: 'btn btn-light' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "jquery", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/messages' %>

    <div class="container">
      <h2 class="my-5 text-center">Meetup App</h2>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_messages.html.erb
<div id="messages" class="toast-container position-absolute p-3">
  <% flash.each do |key, message| %>
    <% if message.present? %>
      <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true" data-controller="flash-message">
        <div class="d-flex">
          <div class="toast-body">
            <%= message %>
          </div>
          <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<%= form_tag(upload_users_path, multipart: true, class: 'w-50 d-flex gap-3 align-items-center justify-content-center') %>
<%= file_field_tag :file, class: 'form-control', accept: 'text/csv', required: true %>
<%= submit_tag 'Upload CSV', class: 'btn btn-primary' %>

<%= link_to "Back to groups", groups_path, class: 'btn btn-light' %>